# Generated by Django 2.2.16 on 2022-08-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220815_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Комментарий'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
    ]
